apps/noticias/urls.py
from django.urls import path
from .views import *

app_name = 'noticias'

urlpatterns = [
    path('', VerTodasLasNoticias.as_view(), name='index'),
    path('crear/', CrearNoticia.as_view(), name="crear"),
    path('ver/<int:pk>', VerNoticia.as_view(), name='ver'),
    path('categorias', ListaCategoria.as_view(), name='categorias'),
    path('categorias/crear', CrearCategoria.as_view(), name='nueva_categoria'),
    path('ver/<int:pk>/comentar', crear_comentario, name="comentar"),
    path('editar/<int:pk>', Editar_Noticia.as_view(), name='editar'),
    path('ver/<int:pk>/comentar/<int:cpk>/editar', actualizar_comentario, name='editar_comentario'),
    path('ver/<int:pk>/like', megusta_noticia, name='megusta'),
    path('ver/<int:pk>/comentarios/<int:cpk>/like', megusta_comentario, name="megusta_comentario"),
    path('ver/<int:pk>/comentarios/<int:cpk>/borrar', borrar_comentario, name="borrar_comentario")
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  
from django.conf.urls.static import static

from apps.noticias.models import Contacto  
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='inicio'),
    path('nosotros', views.about, name='nosotros'),
    path('contacto', views.ContactoVista.as_view(), name='contacto'),
    path('faq', views.faq, 'faq'),
    path('noticias/', include('apps.noticias.urls')),
    path('usuarios/', include('apps.usuarios.urls')),
    path('slides/', include('apps.slides.urls')),
]

if settings.DEBUG:  
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)  

apps/noticias/models.py
import email
from django.db import models
from apps.usuarios.models import *
from django.urls import reverse_lazy
from django.utils.html import strip_tags

class Categoria(models.Model):
	nombre = models.CharField(max_length = 60)
	def __str__(self):
		return self.nombre
	def get_absolute_url(self):
		return reverse_lazy('noticias:index') + "?categoria="+str(self.pk)

class Noticia(models.Model):
	titulo = models.CharField(max_length = 120)
	creado = models.DateTimeField(auto_now_add = True)
	cuerpo = models.TextField()
	autor = models.ForeignKey(Usuario, models.SET_NULL, null = True)
	imagen = models.ImageField(upload_to = 'noticias', null=True, blank = True)
	categoria = models.ForeignKey(Categoria, on_delete = models.CASCADE, null = True)
	visitas = models.IntegerField(default=0)
	likes = models.ManyToManyField(Usuario, blank=True, related_name='likes_noticias')
	
	def __str__(self):
		return self.titulo

	def get_absolute_url(self):
		return reverse_lazy('noticias:ver', args=[self.pk])

	def get_link_comentar(self):
		return reverse_lazy('noticias:comentar', args=[self.pk])

	def get_link_editar(self):
		return reverse_lazy('noticias:editar', args=[self.pk])
		
	def get_resumen(self):
		texto = strip_tags(self.cuerpo)
		if len(texto) >= 50:
			return texto[0:47] + "..."
		return texto

	def get_cantidad_likes(self):
		return len(self.likes.all())

	def get_cantidad_comentarios(self):
		return len(self.comentario_set.all())

	def get_link_like(self):
		return reverse_lazy('noticias:megusta', args=[self.pk])

class Comentario(models.Model):
	noticia = models.ForeignKey(Noticia, on_delete = models.CASCADE)
	texto = models.TextField(max_length=1000, help_text="Deja un comentario")
	creado = models.DateTimeField(auto_now_add = True)
	modificado = models.DateTimeField(auto_now_add = True)
	editado = models.BooleanField(default = False)
	usuario = models.ForeignKey(Usuario, on_delete = models.SET_NULL, null = True)
	likes = models.ManyToManyField(Usuario, blank=True, related_name='likes_comentarios')
	
	
	class Meta:
		ordering = ["creado"]

	def __str__(self):
		return self.texto

	def get_link_editar(self):
		return reverse_lazy('noticias:editar_comentario', args=[self.noticia.pk, self.pk])
	
	def get_link_like(self):
		return reverse_lazy('noticias:megusta_comentario', args=[self.noticia.pk, self.pk])
	
	def get_cantidad_likes(self):
		return len(self.likes.all())

	def get_link_borrar(self):
		return reverse_lazy('noticias:borrar_comentario', args=[self.noticia.pk, self.pk])

class Contacto(models.Model):
	nombre = models.CharField(max_length = 60)
	email = models.EmailField()
	mensaje = models.TextField(max_length=1000, help_text="Mensaje")
	respondido= models.BooleanField(default=False)

apps/noticias/forms.py
from django.forms import *
from .models import *
from django.utils.html import strip_tags
from django.db import models

class NuevaNoticiaForm(ModelForm):
    titulo = CharField(label='Titulo', required=True, widget=TextInput(attrs={'class': 'form-control', 'placeholder': 'Titulo de la noticia'}))
    cuerpo = CharField(label='Cuerpo de la noticia', required=True, widget=Textarea(attrs={
        'class': 'form-control', 
        'placeholder': 'Cuerpo de la noticia'
        }))
    imagen = ImageField(label="Imagen", widget=FileInput(attrs={'class': 'form-control'}))
    categoria = ModelChoiceField(queryset=Categoria.objects.all(), required=False, widget=Select(attrs={'onchange': 'javascript:alternar_visibilidad_nueva_categoria();'}))
    nueva_categoria = CharField(required=False, widget=TextInput(attrs={'placeholder': 'Nombre nueva categoria'}))
    class Meta:
        model = Noticia
        fields = [
            'titulo',
            'cuerpo',
            'categoria',
            'imagen'
        ]
    def clean_cuerpo(self):
        d_cuerpo = self.cleaned_data['cuerpo']
        if len(strip_tags(d_cuerpo)) < 50:
            raise ValidationError('El mínimo de caracteres es de 50')
        return d_cuerpo

    def clean_categoria(self):
        d_categoria = self.cleaned_data['categoria']
        d_nueva_categoria = self.data['nueva_categoria']
        if not d_categoria and not d_nueva_categoria:
            raise ValidationError('Categoria es obligatoria')
        elif d_nueva_categoria:
            categoria = Categoria(nombre=d_nueva_categoria)
            categoria.save()
            return categoria
        return d_categoria
class NuevaCategoriaForm(ModelForm):
    nombre = CharField(label='Nombre de la categoria', required=True, widget=TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre de la categoría'}))
    descripcion = CharField(label='Descripcion', required=True, widget=Textarea(attrs={
        'class': 'form-control', 
        'placeholder': 'Descripcion'
        }))
    class Meta:
        model = Categoria
        exclude = [
            'creado'
        ]

class NuevoComentarioForm(ModelForm):
    texto = CharField(label='Comenta', required=True, widget=Textarea(attrs={
        'class': 'form-control', 
        'rows': 4,
        'placeholder': 'Deja tu comentario'
        }))
    class Meta:
        model = Comentario
        fields = [
            'texto'
        ]


class NuevoContactoForm(ModelForm):
    nombre = CharField(label='Nombre del contacto', required=True, widget=TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Nombre'}))
    email= CharField(label = 'Correo electrónico', required=True, widget=TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Correo electrónico'}))
    mensaje = CharField(label='Comenta', required=True, widget=Textarea(attrs={
        'class': 'form-control',
        'rows':4,
        'placeholder': 'Mensaje'}))

    class Meta:
        model = Contacto     
        fields = [
            'nombre',
            'email',
            'mensaje'
        ]

apps/noticias/views.py
from django.shortcuts import redirect
from django.db.models import Q
from django.views.generic import CreateView, DetailView, ListView, UpdateView
from django.views.generic.base import View
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required

from .models import *
from .forms import *

from datetime import datetime
from django.core.paginator import Paginator

class VerTodasLasNoticias(ListView):
    template_name = 'noticias/noticias.html'
    model = Noticia
    paginate_by = 2

    def get_context_data(self, **kwargs):                
        ctx = super().get_context_data(**kwargs)
        noticias = Noticia.objects.all()
        
        if "q" in self.request.GET.keys():
            q = self.request.GET['q']
            qset = (
                Q(titulo__icontains=q) |
                Q(autor__first_name__icontains=q) |
                Q(categoria__nombre__icontains=q)
            )
            noticias = Noticia.objects.filter(qset).distinct()
            ctx['q'] = q

        elif "ordenar_por" in self.request.GET.keys():
            if self.request.GET['ordenar_por'] == "destacadas":
                noticias = Noticia.objects.all().order_by('-visitas')
            elif self.request.GET['ordenar_por'] == "recientes":
                noticias = Noticia.objects.all().order_by('-creado')
        elif "categoria" in self.request.GET.keys():
            noticias = Noticia.objects.filter(categoria_id=self.request.GET['categoria'])
        elif "mes" in self.request.GET.keys() and "anio" in self.request.GET.keys():
            mes = self.request.GET['mes']
            anio = self.request.GET['anio']
            noticias = Noticia.objects.filter(creado__month=mes, creado__year=anio)


        else:
            noticias = Noticia.objects.all()
        
        
        paginas = Paginator(noticias, 5)
        if "page" in self.request.GET.keys():
            pagina_indice = int(self.request.GET['page'])
            ctx['noticias'] = paginas.page(pagina_indice)
        else:
            ctx['noticias'] = paginas.page(1)
        ctx['categorias'] = Categoria.objects.all()
        ctx['fechas'] = Noticia.objects.all().values('creado__month', 'creado__year').distinct().order_by('-creado__month', '-creado__year')
        return ctx

class CrearNoticia(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    form_class = NuevaNoticiaForm 
    template_name = 'noticias/nueva.html'
    success_url = reverse_lazy('noticias:index')
    
    def test_func(self):
        return self.request.user.is_superuser

    def form_valid(self, form):
        form.instance.autor = self.request.user
        return super(CrearNoticia, self).form_valid(form)

class VerNoticia(DetailView):
    model = Noticia
    template_name = 'noticias/_noticia.html'
    
    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        noticia = self.get_object()
        noticia.visitas+=1
        noticia.save()
        ctx['comment_form'] = NuevoComentarioForm()
        return ctx

class ListaCategoria(ListView):
    model = Categoria
    template_name = 'noticias/categorias.html'

class CrearCategoria(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    form_class = NuevaCategoriaForm
    template_name = 'noticias/nueva_categoria.html'
    success_url = reverse_lazy('noticias:categorias')

    def test_func(self):
        return self.request.user.is_superuser

def crear_comentario(request, pk):
    if request.method == "POST":
        form = NuevoComentarioForm(data = request.POST)
        form.instance.usuario = request.user
        noticia = Noticia.objects.get(pk=pk)
        form.instance.noticia = noticia
        if form.is_valid():
            form.save()
        else:
            return redirect('noticias:ver', pk, { 'comment_form': form})
    return redirect('noticias:ver', pk)

class Editar_Noticia(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Noticia
    template_name = 'noticias/editar.html'
    form_class = NuevaNoticiaForm
    def test_func(self):
        return self.request.user.is_superuser

def actualizar_comentario(request, pk, cpk):
    if request.method == "POST":
        form = NuevoComentarioForm(data = request.POST)
        comentario = Comentario.objects.get(pk=cpk)
        if form.is_valid() and comentario.usuario == request.user:
            comentario.texto = form.instance.texto
            comentario.editado = True
            comentario.modificado = datetime.now()
            comentario.save()
        else:
            return redirect('noticias:ver', pk, { 'comment_form': form})
    return redirect('noticias:ver', pk)

@login_required
def megusta_noticia(request, pk):
    if request.method == "POST":
        noticia = Noticia.objects.get(pk=pk)
        if request.user in noticia.likes.all():
            noticia.likes.remove(request.user)
        else:
            noticia.likes.add(request.user)
    return redirect('noticias:ver', pk)
    
@login_required
def megusta_comentario(request, pk, cpk):
    if request.method == "POST":
        comentario = Comentario.objects.get(pk=cpk)
        if request.user in comentario.likes.all():
            comentario.likes.remove(request.user)
        else:
            comentario.likes.add(request.user)
    return redirect('noticias:ver', pk)

@login_required
def borrar_comentario(request, pk, cpk):
    if request.method == "POST":
        comentario = Comentario.objects.get(pk=cpk)
        if request.user == comentario.usuario:
            comentario.delete()
    return redirect('noticias:ver', pk)

templates/noticias/_modal_borrar.html
<div style="top: 80px;" class="modal fade" id="borrar_modal{{comentario.pk}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Confirmar eliminacion</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p>Estás seguro de que deseas eliminar este comentario?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
          <form method="post" action="{{comentario.get_link_borrar}}"> 
            {% csrf_token %}
            <button type="submit" class="btn btn-primary">Confirmar</button>
          </form>
        </div>
      </div>
    </div>
  </div>

templates/noticias/_noticia.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container-fluid flex-wrap px-4">
    <div class="h2">
        {% if noticia.categoria %}
        {{noticia.categoria}}
        {% else %}
        Sin categoría
        {% endif %}
    </div>
    <div class="h1">{{noticia.titulo}}
        {% if user.is_authenticated and user.is_superuser %}
        <a href="{{noticia.get_link_editar}}" class="btn btn-success">Editar</a>
        {% endif %}
    </div>
    <small class="text-muted">Publicado por 
        {% if noticia.autor %}
        {{noticia.autor|upper}}
        {% else %}
        An&oacute;nimo
        {% endif %}
        | {{noticia.creado|timesince}}</small>
    <div>
        {% if noticia.imagen %}
        <img src="{{noticia.imagen.url}}" alt="{{noticia.titulo}}" width="100%" class="img-fluid slider-img">
        {% endif %}
    </div>
    <div>{{noticia.cuerpo | safe}}</div>
    <hr>
    <div>
        <form action="{{noticia.get_absolute_url}}/like" class="d-inline" method="POST">
            {% csrf_token %}
            {% if user in noticia.likes.all %}
            <button class="btn bi bi-heart-fill"
                style="color: red; font-size: 1.5rem;">{{noticia.get_cantidad_likes}}</button>
            {% else %}
            <button class="btn bi bi-heart"
                style="color: red; font-size: 1.5rem;">{{noticia.get_cantidad_likes}}</button>
            {% endif %}
        </form>
        <div class="dropdown d-inline">
            <a class="bi bi-share btn dropdown-toggle text-muted" href="#" role="button" data-bs-toggle="dropdown"
                aria-expanded="false">
            </a>

            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#">Facebook</a></li>
                <li><a class="dropdown-item" href="#">Twitter</a></li>
                <li><a class="dropdown-item" href="#">Copiar enlace</a></li>
            </ul>
        </div>
    </div>
    <div>
        <h4>Comentarios <span style="font-size: 1rem;">{{noticia.get_cantidad_comentarios}}</span></h4>
        {% if noticia.comentario_set.all %}
        {% for comentario in noticia.comentario_set.all %}
        <form id="id_texto{{comentario.pk}}" action="{{comentario.get_link_editar}}" method="POST" class="d-none">
            {% csrf_token %}
            <textarea name="texto" class="form-control" rows="4">{{comentario.texto}}</textarea>
            <button class="btn btn-primary" type="submit">Guardar</button>
            <button class="btn btn-danger" type="reset"
                onclick="cancelar_edicion('{{comentario.pk}}');">Cancelar</button>
        </form>
        <div class="border" id="id_comentario{{comentario.pk}}">
            <div class="p-2">{{comentario.texto}}</div>
            <div>
                <small class="text-muted">
                    <form action="{{comentario.get_link_like}}" class="d-inline" method="POST">
                        {% csrf_token %}
                        {% if user in comentario.likes.all %}
                        <button class="btn bi bi-heart-fill"
                            style="color: red; font-size: 1rem;">{{comentario.get_cantidad_likes}}</button>
                        {% else %}
                        <button class="btn bi bi-heart"
                            style="color: red; font-size: 1rem;">{{comentario.get_cantidad_likes}}</button>
                        {% endif %}
                    </form>
                    <b>{{comentario.usuario|upper}}</b> | {{comentario.modificado|timesince}}
                    {% if comentario.editado %}
                    | <b>Editado</b>
                    {% endif %}
                    {% if user.is_authenticated and user == comentario.usuario %}
                    | <a href="javascript:editar({{comentario.pk}});"><b>Editar</b></a>
                    | <a href="javascript:void(0);"  data-bs-toggle="modal" data-bs-target="#borrar_modal{{comentario.pk}}"><b>Borrar</b></a>
                    {% include 'noticias/_modal_borrar.html' %}
                    {% endif %}
                </small>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <i>No hay comentarios, se el primero!</i>
        {% endif %}
        <hr>
        {% if user.is_authenticated %}
        <form action="{{noticia.get_link_comentar}}" method="post">
            {% csrf_token %}
            {{ comment_form }}
            <button class="btn btn-primary" type="submit">Comentar</button>
        </form>
        {% else %}
        <p><a href="{% url 'login'%}?next={{request.path}}">Inicia sesi&oacute;n</a> para comentar</p>
        {% endif %}
    </div>
</div>
<script src="{% static 'js/comentario.js' %}" type="text/javascript"></script>
{% endblock content %}

templates/noticias/categorias.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="mx-4 p-4">
    <div class="h1">Categor&iacute;as</div>
    <div>
        <a href="{% url 'noticias:nueva_categoria' %}" class="btn btn-success">Nueva categor&iacute;a</a>
    </div>
    <div>
        {%if categoria_list %}
        {% for c in categoria_list %}
        <div class="list-group">
            <a href="#" class="list-group-item list-group-item-action">
                <b>{{c.nombre}}</b>
                <p>{{c.descripcion}}</p>
            </a>
            
        </div>
        {% endfor %}
        {% else %}
        <i>No hay categorías</i>
        {% endif %}
    </div>
</div>
{% endblock content %}

templates/noticias/editar.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="mx-4 flex-wrap py-1">
    <div class="h2">Editar noticia</div>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-primary form-control" value="submit" type="submit">Publicar</button>
    </form>
</div>
<script src="https://cdn.jsdelivr.net/npm/sceditor@3/minified/formats/bbcode.min.js"></script>
<script>
    var textarea = document.getElementById('id_cuerpo');
    sceditor.create(textarea, {
        format: 'html',
        style: 'https://cdn.jsdelivr.net/npm/sceditor@3/minified/themes/content/default.min.css',
        emoticonsRoot: '/static/'
    });
</script>
{% endblock content %}

templates/noticias/noticias.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<main class="container-fluid d-flex flex-row gap-1">
    <div class="bg-light-dark">
        <div class="bg-white sticky-top z-index-1">
            <ul class="list-unstyled ps-0 px-3 collapse collapse-horizontal" style="width: 200px; top:90px;" id="barra_lateral">
                {% if user.is_authenticated and user.is_superuser %}
                <li class="mb-1">
                    <a href="{% url 'noticias:crear' %}" class="btn btn-success"><i class="bi bi-plus-square"></i> Crear
                        noticia</a>
                </li>
                {% endif %}
                <li class="mb-1">
                    <br>
                    <div>
                        <ul class="h4" style="list-style: none">
                            <li><a href="{% url 'noticias:index' %}" class="link-dark rounded">Todas</a></li>       
                        </ul>
                    </div>
                    <br>
                    <hr></hr>
                    <br>
                    <div class="h4">
                        Por Categor&iacute;as
                    </div>
                    <div>
                        <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                            <li><a href="{% url 'noticias:index' %}?ordenar_por=destacadas" class="link-dark rounded">Más destacado</a></li>
                            {% if categorias %}
                            {% for categoria in categorias %}
                            <li><a href="{{categoria.get_absolute_url}}" class="link-dark rounded">{{categoria.nombre}}</a></li>
                            {% endfor %}
                            {% endif %}
                        </ul>
                    </div>
                    <br>
                    <hr></hr>
                    <br>
                    <div class="h4">
                        Por Fechas
                    </div>
                    <div>
                        <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                            <li><a href="{% url 'noticias:index' %}?ordenar_por=recientes" class="link-dark rounded">Más recientes</a></li>
                            {% if fechas %}
                            {% for fecha in fechas %}
                            <li><a href="{% url 'noticias:index' %}?mes={{fecha.creado__month}}&anio={{fecha.creado__year}}" class="link-dark rounded">{{fecha.creado__month}} / {{fecha.creado__year}}</a></li>
                            {% endfor %}
                            {% endif %}
                        </ul>
                    </div>
                    <br>
                    <br>
                </li>
            </ul>
            <button class="btn btn-secondary" type="button" data-bs-toggle="collapse" data-bs-target="#barra_lateral" aria-expanded="false" aria-controls="collapseWidthExample">
                ...
            </button>
        </div>
    </div>
    <div class="container-fluid p-4 mt-0">
        {% if q %}
        <div class="h1">Resultados para: "{{q|escape}}"</div>
        {% else %}
        <div class="h1">Noticias</div>
        {% endif %}
        {% if noticias %}
        {% for n in noticias %}
        <div class="card mb-4 box-shadow-3">
            {% if n.imagen %}
            <img src="{{ n.imagen.url }}" class="card-img-top slider-img" alt="{{n.titulo}}">
            {% endif %}
            <div class="card-body">
                <h5 class="card-title"><a href="{{n.get_absolute_url}}">{{n.titulo}}</a></h5>
                <p class="card-text">{{n.get_resumen}}</p>
            </div>
            <div class="card-footer">
                <small class="text-muted">
                    {% if n.categoria %}
                    {{n.categoria}}
                    {% else %}
                    Sin categor&iacute;a
                    {% endif %}
                    |
                    {% if n.autor %}
                    {{n.autor}}
                    {% else %}
                    An&oacute;nimo
                    {% endif %}
                    | {{ n.creado|timesince }}</small>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <div class="h3">No hay noticias</div>
        {% endif %}
    <div class="pagination">
        <span class="step-links">
        {% if noticias.has_previous %}
            <a href="?page=1">&laquo; Primera</a>
            <a href="?page={{ noticias.previous_page_number }}">Anterior</a>
        {% endif %}

        <span class="current">
            Pagina {{ noticias.number }} de {{ noticias.paginator.num_pages }}.
        </span>

        {% if noticias.has_next %}
            <a href="?page={{ noticias.next_page_number }}">Siguiente</a>
            <a href="?page={{ noticias.paginator.num_pages }}">Ultima &raquo;</a>
        {% endif %}
        </span>
    </div>
</main>
{% endblock content %}

templates/noticias/nueva.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="mx-4 flex-wrap py-1">
    <div class="h2">Crear noticia</div>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.errors}}
        <div class="mb-3">
        {{form.titulo.label_tag}}
        {{form.titulo.errors}}
        {{form.titulo}}
        </div>
        <div class="mb-3">
        {{form.cuerpo.label_tag}}
        {{form.cuerpo.errors}}
        {{form.cuerpo}}
        </div>
        <div class="mb-3">
        {{form.categoria.label_tag}}
        {{form.categoria.errors}}
        {{form.categoria}}
        {{form.nueva_categoria}}
        </div>
        <div class="mb-3">
        {{form.imagen.label_tag}}
        {{form.imagen.errors}}
        {{form.imagen}}
        </div>
        <button class="btn btn-primary form-control" value="submit" type="submit">Publicar</button>
    </form>
</div>
<script src="https://cdn.jsdelivr.net/npm/sceditor@3/minified/formats/bbcode.min.js"></script>
<script>
    var textarea = document.getElementById('id_cuerpo');
    sceditor.create(textarea, {
        format: 'html',
        style: 'https://cdn.jsdelivr.net/npm/sceditor@3/minified/themes/content/default.min.css',
        emoticonsRoot: '/static/'
    });
</script>
<script src="{% static 'js/noticia.js' %}" type="text/javascript">
</script>
{% endblock content %}

templates/noticias/nueva_categoria.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="mx-4 p-4">
    <div class="h1">Crear categor&iacute;a</div>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-primary" type="submit">Crear categoría</button>
    </form>
</div>
{% endblock content %}