apps/slides/urls.py
from django.urls import path
from .views import *

app_name = 'slides'

urlpatterns = [
    path('', ListarSlidesVista.as_view(), name="index"),
    path('crear', NuevoSlideVista.as_view(), name="crear_slide"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  
from django.conf.urls.static import static

from apps.noticias.models import Contacto  
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='inicio'),
    path('nosotros', views.about, name='nosotros'),
    path('contacto', views.ContactoVista.as_view(), name='contacto'),
    path('faq', views.faq, 'faq'),
    path('noticias/', include('apps.noticias.urls')),
    path('usuarios/', include('apps.usuarios.urls')),
    path('slides/', include('apps.slides.urls')),
]

if settings.DEBUG:  
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)  

apps/slides/models.py
from django.db import models

# Create your models here.

class Slide(models.Model):
    texto = models.CharField(max_length = 250, null = True, blank = True)
    imagen = models.ImageField(upload_to = 'slides', null=True, blank = True)
    creado = models.DateField(auto_now_add = True)

apps/slides/forms.py
from django.forms import *
from .models import *

class NuevoSlideFormulario(ModelForm):
    texto = CharField(label='Texto de presentación', required=True, widget=Textarea(attrs={
        'class': 'form-control', 
        'rows': 4,
        'placeholder': 'Texto de presentación'
        }))
    class Meta:
        model = Slide
        fields = [
            'texto',
            'imagen',
        ]

apps/slides/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import CreateView, ListView
from django.urls import reverse_lazy
from .forms import *
from .models import *

class NuevoSlideVista(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    form_class = NuevoSlideFormulario
    template_name = 'slides/nuevo.html'
    success_url = reverse_lazy('slides:index')
    def test_func(self):
        return self.request.user.is_superuser

class ListarSlidesVista(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = Slide
    template_name = 'slides/slides.html'
    def test_func(self):
        return self.request.user.is_superuser

templates/slides/nuevo.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="mx-4 flex-wrap py-1">
    <div class="h2">Crear slide</div>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-primary form-control" value="submit" type="submit">Guardar</button>
    </form>
</div>
{% endblock content %}

templates/slides/slide_show.html
<div id="carouselExampleDark" class="carousel carousel-dark slide m-4" data-bs-ride="carousel">
    <div class="carousel-inner">
        {% if slides %}
        {% for slide in slides %}
        <div class="carousel-item active" data-bs-interval="10000">
            <img src="{{slide.imagen.url}}" class="d-block w-100 slider-img" alt="{{slide.texto}}">
            <div class="carousel-caption d-none d-md-block">
                <h3 class="text-white">
                    {{slide.texto}}
                </h3>
            </div>
        </div>
        {% endfor %}
        {% else %}
        {% include 'slides/slides_default.html' %}
        {% endif %}
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

templates/slides/slides.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="mx-4 flex-wrap py-1">
    <div class="h2">Lista de Slides</div>
    {% for slides in slide_list %}
    <div class="h2">{{ slides.texto }}</div>
    <div><img src="{{ slides.imagen.url }}" alt="{{slides.texto}}"></div>
    {% endfor %}
</div>
{% endblock content %}

templates/slides/slides_default.html
<div class="carousel-item active" data-bs-interval="10000">
    <img src="static/img/imp1.jpg" class="d-block w-100 slider-img" alt="...">
    <div class="carousel-caption d-none d-md-block">
        <h3 class="text-white">
            Nuestra meta es promover el Arte y el Turismo, rescatando, revalorizando e incluyendo todas las
            manifestaciones artísticas y culturales, en salvaguarda de nuestra identidad, y en defensa del
            medio
            ambiente
        </h3>
    </div>
</div>
<div class="carousel-item" data-bs-interval="10000">
    <img src="static/img/imp2.jpg" class="d-block w-100 slider-img" alt="...">
    <div class="carousel-caption d-none d-md-block">
        <h2 class="text-white">
            La Fundación Amigos del Arte y Turismo, con Personería Jurídica Nº452/14 es una Entidad no
            lucrativa, con el fin de vincular las expresiones culturales de la región, la idiosincrasia de
            la
            gente y el turismo a través del ARTE
        </h2>
    </div>
</div>
<div class="carousel-item" data-bs-interval="10000">
    <img src="static/img/imp3.jpg" class="d-block w-100 slider-img" alt="...">
    <div class="carousel-caption d-none d-md-block">
        <h2 class="text-white">
            Nos reconocemos como parte de “El Impenetrable”, su cultura y su gente. Por eso, buscamos dar a
            conocer nuestra región, su riqueza, sus leyendas, su arte y su poesía, que invitan a recorrer
            lugares como la FIDELIDAD, MISIÓN NUEVA POMPEYA, LA CANGAYÉ, LAS RUINAS DEL Km 71 que nos hablan
            de
            nuestra historia y nuestra gente.
        </h2>
    </div>
</div>