apps/noticias/urls.py
from django.urls import path
from .views import *

app_name = 'noticias'

urlpatterns = [
    path('', VerTodasLasNoticias.as_view(), name='index'),
    path('crear/', CrearNoticia.as_view(), name="crear"),
    path('ver/<int:pk>', VerNoticia.as_view(), name='ver'),
    path('categorias', ListaCategoria.as_view(), name='categorias'),
    path('categorias/crear', CrearCategoria.as_view(), name='nueva_categoria'),
    path('ver/<int:pk>/comentar', crear_comentario, name="comentar"),
    path('editar/<int:pk>', Editar_Noticia.as_view(), name='editar'),
    path('ver/<int:pk>/comentar/<int:cpk>/editar', actualizar_comentario, name='editar_comentario'),
    path('ver/<int:pk>/like', megusta_noticia, name='megusta'),
    path('ver/<int:pk>/comentarios/<int:cpk>/like', megusta_comentario, name="megusta_comentario"),
    path('ver/<int:pk>/comentarios/<int:cpk>/borrar', borrar_comentario, name="borrar_comentario")
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  
from django.conf.urls.static import static

from apps.noticias.models import Contacto  
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='inicio'),
    path('nosotros', views.about, name='nosotros'),
    path('contacto', views.ContactoVista.as_view(), name='contacto'),
    path('faq', views.faq, 'faq'),
    path('noticias/', include('apps.noticias.urls')),
    path('usuarios/', include('apps.usuarios.urls')),
    path('slides/', include('apps.slides.urls')),
]

if settings.DEBUG:  
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)  

templates/base.html
{% load static %}
<html>

<head>
    <title>Fundacion Amigos del Arte y Turismo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="icon" href="{% static 'favicon.png' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sceditor@3/minified/themes/default.min.css" />
    <script src="https://cdn.jsdelivr.net/npm/sceditor@3/minified/sceditor.min.js"></script>

    <!--Bootstrap 5.2-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>
    <!--Font Awesome-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/slider.css' %}">
    <link rel="stylesheet" href="{% static 'css/redes.css' %}">
    <link rel="stylesheet" href="{% static 'css/noticias.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
</head>

<body>
    <nav class="header navbar navbar-expand-lg flex-wrap flex-lg-nowrap navbar-light bg-light sticky-top border-bottom">
        <div class="container-fluid">
            <a class="navbar-brand py-0" href="{% url 'inicio' %}"><img src="{% static 'img/logo1.png' %}" alt=""
                    height="70px"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-md-auto">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'inicio' %}">Inicio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'nosotros' %}">Quienes somos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'contacto' %}">Contacto</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="{% url 'noticias:index' %}" id="navbarDropdown"
                            role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Noticias
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'noticias:index' %}?ordenar_por=recientes">Más recientes</a></li>
                            <li><a class="dropdown-item" href="{% url 'noticias:index' %}?ordenar_por=destacadas">Más destacadas</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="{% url 'noticias:index' %}">Todas las noticias</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <form class="d-flex" action="{% url 'noticias:index' %}" method="GET">
                            <input class="form-control me-2" type="search" name="q" placeholder="Buscar" aria-label="Search" value="{{q|escape}}">
                            <button class="btn btn-outline-success" type="submit"><i class="bi bi-search"></i></button>
                        </form>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="javascript:void(0);" id="navbarDropdown_profile"
                            role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="bi bi-person-circle"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown_profile">
                            {% if user.is_authenticated %}
                            {% if user.is_superuser %}
                            <li><a class="dropdown-item" href="{% url 'admin:index' %}">Administraci&oacute;n del
                                    sitio</a></li>
                            {% endif %}
                            <li><a class="dropdown-item" href="{% url 'perfil' user %}">Perfil</a></li>
                            <li><a class="dropdown-item" href="#">Ajustes</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="{% url 'logout' %}">Cerrar sesión</a></li>
                            {% else %}
                            <li><a class="dropdown-item" href="{% url 'login' %}">Iniciar sesión</a></li>
                            <li><a class="dropdown-item" href="{% url 'registro' %}">Registrarse</a></li>
                            {% endif %}
                        </ul>
                    </li>
                </ul>

            </div>
        </div>
    </nav>
    {% block content %}
    {% endblock content %}
    <footer class="px-4">
        <div class="card-group">
            <div class="card border-0">
                <h5>Navegación</h5>
                <ul class="nav flex-column">
                    <li class="nav-item mb-2"><a href="{% url 'inicio' %}" class="nav-link p-0 text-muted">Inicio</a>
                    </li>
                    <li class="nav-item mb-2"><a href="{% url 'nosotros' %}" class="nav-link p-0 text-muted">Quienes
                            somos</a></li>
                    <li class="nav-item mb-2"><a href="{% url 'contacto' %}"
                            class="nav-link p-0 text-muted">Contacto</a></li>
                    <li class="nav-item mb-2"><a href="#faq" class="nav-link p-0 text-muted">FAQs</a></li>
                </ul>
            </div>
            <div class="card border-0">
                <h5>Noticias</h5>
                <ul class="nav flex-column">
                    <li class="nav-item mb-2"><a href="{% url 'noticias:index' %}?ordenar_por=recientes" class="nav-link p-0 text-muted">Más recientes</a></li>
                    <li class="nav-item mb-2"><a href="{% url 'noticias:index' %}?ordenar_por=destacadas" class="nav-link p-0 text-muted">Más destacadas</a></li>
                    {% if categorias %}
                    {% for categoria in categorias %}
                    <li class="nav-item mb-2"><a href="{{categoria.get_absolute_url}}" class="nav-link p-0 text-muted">{{categoria.nombre}}</a></li>
                    {% endfor %}
                    {% endif %}
                </ul>
            </div>
            <div class="card border-0">
                {% if user.is_authenticated %}
                <div>
                    <div class="h3">Gracias por formar parte!</div>
                </div>
                {% else %}
                <form>
                    <h5>Suscr&iacute;bete a nuestro newsletter</h5>
                    <p>Recibe noticias mensualmente!</p>
                    <div class="d-flex w-100 gap-2">
                        <label for="newsletter1" class="visually-hidden">Email address</label>
                        <input id="newsletter1" type="text" class="form-control" placeholder="Email address">
                        <button class="btn btn-primary" type="button">Subscribe</button>
                    </div>
                </form>
                {% endif %}
            </div>
        </div>
        <div class="d-flex flex-wrap justify-content-between align-items-center py-3 m-4 border-top">
            <div class="col-md-4 d-flex align-items-center">
                <a href="{% url 'inicio' %}" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
                    <img src="{% static 'favicon.png' %}" alt="Logo - Fundacion amigos del arte y turismo"
                        height="24px">
                </a>
                <span class="text-muted">© 2021 Fundacion Amigos del Arte y Turismo</span>
            </div>

            <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
                <li class="ms-3">
                    <a class="text-muted envelope" href="mailto:info@amigosdelarteyturismo.org">
                        <i class="bi bi-envelope-at-fill"></i>
                    </a>
                </li>
                <li class="ms-3"><a class="text-muted instagram"
                        href="https://www.instagram.com/invites/contact/?i=13h4oeeulvmes&utm_content=okk3z6q"
                        target="_blank">
                        <i class="bi bi-instagram"></i>
                    </a>
                </li>
                <li class="ms-3">
                    <a class="text-muted facebook" href="https://www.facebook.com/EscultoresenelImpenetrable"
                        target="_blank">
                        <i class="bi bi-facebook"></i>
                    </a>
                </li>
            </ul>
        </div>
    </footer>
</body>

</html>

templates/contacto.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="px-4">
        <form method="POST" class="p-4 shadow p-3 mb-5 bg-body rounded border-1" style="max-width: 500px; margin: auto;">
           {{form.errors}}
           {% csrf_token %}
            <div class="mb-3 h3">
                Contáctanos
            </div>
            <div class="mb-3">
                <label for="nameInput" class="form-label">Nombre y apellido</label>
                {{form.nombre}}
                {{form.nombre.errors}}
            </div>
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Correo electrónico</label>
                {{form.email}}
                {{form.email.errors}}
            </div>
            <div class="mb-3">
                <label for="textarea1" class="form-label">D&eacute;janos tu mensaje</label>
                {{form.mensaje}}
                {{form.mensaje.errors}}
            </div>
            <div class="mb-3 form-check">
                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                <label class="form-check-label" for="exampleCheck1">Suscribirse a nuestro newsletter</label>
            </div>
            <button type="submit" class="btn btn-primary">Enviar</button>
        </form>
    </div>
</main>
{% endblock content %}

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<main class="container-fluid flex-wrap">
    <!--Carousel-->
    {% include 'slides/slide_show.html' %}
    <!--Noticias-->
    <div class="p-4">
        <div class="h1">Últimas Noticias</div>
        <div class="card-group gap-3">
            {% for n in ultimas_noticias|slice:":3" %}
            <div class="card box-shadow-3">
                <img src="{{n.imagen.url}}" class="card-img-top thumbnail" alt="{{n.titulo}} | {{n.categoria}}">
                <div class="card-body">
                    <h5 class="card-title"><a href="{{n.get_absolute_url}}">{{n.titulo}}</a></h5>
                    <p class="card-text">{{n.get_resumen}}</p>
                </div>
                <div class="card-footer">
                    <small class="text-muted">{{n.creado|timesince}}</small>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="h1">Noticias más destacadas</div>
        <div class="card-group gap-3">
            {% for n in noticias_destacadas|slice:":3" %}
            <div class="card box-shadow-3">
                <img src="{{n.imagen.url}}" class="card-img-top thumbnail" alt="{{n.titulo}} | {{n.categoria}}">
                <div class="card-body">
                    <h5 class="card-title"><a href="{{n.get_absolute_url}}">{{n.titulo}}</a></h5>
                    <p class="card-text">{{n.get_resumen}}</p>
                </div>
                <div class="card-footer">
                    <small class="text-muted">{{n.creado|timesince}}</small>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</main>
{% endblock content %}

templates/nosotros.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<main>  
    <img src="{% static 'img/imp6.jpg' %}" class="img-fluid"/>
    <div class="db-main order-1 p-4">
        <div class="p-3">
            <div class="text-center">
            <div class="h1">¿Qui&eacute;nes somos?</div>
            </div>
            <div class="bd-lead">
                La Fundación Amigos del Arte y Turismo, con Personería Jurídica Nº452/14 es una entidad no lucrativa, con el
                fin
                de vincular las expresiones culturales de la región, la idiosincrasia de la gente y el turismo a través del
                ARTE.
                Nuestra meta es promover el Arte y el Turismo, rescatando, revalorizando e incluyendo todas las
                manifestaciones
                artísticas y culturales, en salvaguarda de nuestra identidad, y en defensa del medio ambiente.
                Geográficamente ubicados en el Departamento General Güemes de la provincia del Chaco, en la Puerta del
                Impenetrable, con una comunidad integrada por pueblos originarios de distintas etnias, criollos y
                descendientes
                de inmigrantes de distintos países de Europa.
                Nos reconocemos como parte de “El Impenetrable”, su cultura y su gente. Por eso, buscamos dar a conocer
                nuestra
                región, su riqueza, leyendas, arte y poesía, que invitan a recorrer lugares como La Fidelidad,
                Misión Nueva Pompeya, La Cangayé y las ruidas del km 71 que nos hablan de nuestra historia y nuestra gente.
    
            </div>
        </div>
        <div class="p-3">
            <div class="text-center">
            <div class="h1">Nuestra misi&oacute;n</div>
            </div>
            <div class="">
                Ser partícipes del desarrollo cultural, brindar oportunidades y capacitación del Arte y hacer del mismo un
                atractivo turístico.
            </div>
        </div>
        <div class="p-3">
            <div class="text-center">
            <div class="h1">Nuestra visi&oacute;n</div>
            </div>
            <div class="">
                Sacar a la luz lo que late en el Impenetrable.
            </div>
        </div>
        <div class="p-3">
            <div class="text-center">
            <div class="h1">Objetivos Generales</div>
            </div>
            <div class="">
                <ul>
                    <li>Velar por nuestro rico patrimonio cultural y dar a conocer a todos los que nos visiten las
                        diferentes expresiones de nuestra identidad.
                    </li>
                    <li>Estimular y divulgar el arte y el turismo y fomentarlos como fuente de superación de las personas de
                        nuestra comunidad y darlo a conocer.
                    </li>
                </ul>
            </div>
        </div>
        <div class="p-3">
            <div class="text-center">
            <div class="h1">Objetivos Espec&iacute;ficos</div>
            </div>
            <div class="">
                <ul>
                    <li>
                        Organizar eventos de cualquier naturaleza con carácter regional, nacional e internacional en pro del
                        desarrollo del arte y el turismo.
                    </li>
                    <li>
                        Impulsar el turismo revitalizando las artes tradicionales y la industria artesanal de la zona a
                        través de la comercialización de los productos locales y de otros recursos de aquellas localidades
                        marginadas por la desindustrialización o el aislamiento.
                    </li>
                    <li>
                        Proteger y restaurar nuestro patrimonio cultural y artístico.
                    </li>
                    <li>
                        Organizar encuentros culturales, espectáculos y otros acontecimientos que contribuyan a divulgar
                        nuestra idiosincrasia.
                    </li>
                    <li>
                        Desarrollar programas de formación y capacitación que estén íntimamente relacionados con la misión
                        de la fundación.
                    </li>
                    <li>
                        Generar muestras públicas de contemplación de técnicas y observación de creación de obras artísticas
                        celebrando exposiciones temáticas con artistas invitados.
                    </li>
                    <li>
                        Generar muestras públicas de contemplación de técnicas y observación de creación de obras artísticas
                        celebrando exposiciones temáticas con artistas invitados.
                    </li>
                    <li>
                        Ayudar y colaborar en proyectos públicos o privados en los que se combinen cultura y turismo (rutas
                        literarias, rutas históricas, etc.) con mayor intensidad en lo que se refiere a la colaboración
                        recíproca con otras Fundaciones culturales o de otros fines que coadyuven en la promoción de la
                        cultura.
                    </li>
                    <li>
                        Apoyar proyectos educativos, culturales destinados a destacar la importancia de la cultura.
                    </li>
                    <li>
                        Desarrollar e impulsar el turismo interior en el Impenetrable en sintonía con la tendencia en alza
                        del turismo alternativo (cultura y naturaleza).
                    </li>
                    <li>
                        Promover actividades de formación en el conocimiento de la cultura.
                    </li>
                    <li>
                        Potenciar Castelli y su región como destino turístico.
                    </li>
                </ul>
            </div>
        </div>
        <div class="p-3">
            <div class="h1">Conformación de la actual comisi&oacute;n</div>
            <div class="bd-lead">
                <ul>
                    <li><b>Presidente</b>: DG. Rene Bertolucci</li>
                    <li><b>Vicepresidente</b>: Arq. Yolanda M. Rausch</li>
                    <li><b>Secretaria</b>: Prof. Marisa Santamaría</li>
                    <li><b>Tesorera</b>: Prof. Elena Díaz de Lázara</li>
                    <li><b>Vocal</b>: Dr. Jorge Kleisinger</li>
                </ul>
            </div>
        </div>
        <div class="p-3">
            <div class="text-center">
            <div class="h1">Ubicación</div>
            </div>
            <div>
                <iframe
                    src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d896.9209838284005!2d-60.6207856!3d-25.9456008!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94404cfba5224f0b%3A0xbe1797f5f1777f83!2sFundaci%C3%B3n%20Amigos%20del%20Arte%20y%20Turismo!5e0!3m2!1ses!2sar!4v1669693704333!5m2!1ses!2sar"
                    width="100%" height="200" style="border:0;" allowfullscreen="" loading="lazy"
                    referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>
        </div>
    </div>
    <div class="text-center">
        <img src="{% static 'img/logo2.jpg' %}" class=".img-fluid" width="50px" height="50px" />
    </div>
</main>
{% endblock content%}